### ISSUE TITLE
Move projects to Guaka github profile

### ISSUE THREAD

**Issue by nsomar** [nsomar/Guaka#43]
Move them here https://github.com/getGuaka

- [x] Environment: https://github.com/oarrabi/env
- [x] File: https://github.com/oarrabi/FileSystem
- [x] Regex: https://github.com/oarrabi/regex
- [x] Runing apps: https://github.com/oarrabi/Runner
- [ ] Main: https://github.com/nsomar/Guaka

**Comment by thii** [comment]
@nsomar Will you be able to do this? You can just move the repos, and I'll do the rest 😀

**Comment by thii** [comment]
Btw, do you prefer to keep the Guaka repo in your personal profile?
